[package]
name = "rustructure"
version = "0.1.0"
edition = "2024"

[dependencies]
fuzzy-matcher = "0.3.7"
priority-queue = "2.1.2"
proc-macro2 = { version = "1.0.93", features = ["span-locations"] }
ratatui = "0.29.0"
rust_search = "2.1.0"
syn = { version = "2.0.98", features = ["full"] }
